[package]
name = "wiki-path"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
jiff = "0.1.23"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
